highlighter: pygments
baseurl: /soot

title: Soot
description: Soot - A framework for analyzing and transforming Java and Android applications
google_analytics: UA-53612145-1
show_downloads: true
theme: jekyll-theme-slate